version: '3'

services:
  sender-service:
    build: ./
    ports:
      - 5001:8080
    depends_on:
      - db
  db:
    image: mysql
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: ueducation